bonus/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.user_bonus, name="user_bonus"),
     path("dashboard", views.dashboard_bonus, name="dashboard_bonus"),
     path("dashboard/<int:pk>", views.dashboard_bonus, name="dashboard_bonus")
]

faq/urls.py
from django.urls import path
from . import views

urlpatterns = [
       
         path('dashboard',views.dashboard_faq, name='dashboard_faq'),
          path('dashboard/delete/<int:pk>',views.dashboard_delete_faq, name='dashboard_delete_faq'),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('',views.user_dashboard, name='user_dashboard'),
        path('dashboard',views.admin_dashboard, name='admin_dashboard'),
         path('dashboard/users',views.admin_dashboard_user, name='admin_dashboard_user'),
          path('dashboard/user/<int:pk>',views.admin_dashboard_user_detail, name='admin_dashboard_user_detail'),
           path('dashboard/admin_add_user_deposit/<int:pk>',views.admin_add_user_deposit, name='admin_add_user_deposit'),
        path('dashboard/admin_add_user_withdrawal/<int:pk>',views.admin_add_user_withdrawal, name='admin_add_user_withdrawal'),
        path('dashboard/user_password_reset_by_admin/<int:pk>',views.user_password_reset_by_admin, name='user_password_reset_by_admin'),
        path('dashboard/admin_make_investment_for_user/<int:pk>',views.admin_make_investment_for_user, name='admin_make_investment_for_user'),
        path('dashboard/editbalance/<int:pk>',views.editbalance, name='editbalance'),
        path('dashboard/user_profile_update_by_admin/<int:pk>',views.user_profile_update_by_admin, name='user_profile_update_by_admin'),
        path('dashboard/delete/<int:pk>',views.delete_user, name='delete_user'),
]

vest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('user.urls')),
    path('deposit/',include('deposit.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('withdraw/',include('withdraw.urls')),
    path('transfer/',include('transfer.urls')),
    path('kyc/',include('kyc.urls')),
    path('transaction/',include('transaction.urls')),
    path('bonus/',include('bonus.urls')),
    path('penalty/',include('penalty.urls')),
    path('contact/',include('contact.urls')),
    path('referral/',include('referral.urls')),
    path('plans/',include('investmentplan.urls')),
    path('faq/',include('faq.urls')),
    path('testimony/',include('testimony.urls')),
    path('statistic/',include('statistic.urls')),
    path('notification/',include('notification.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
  
handler404 = 'user.views.my_custom_page_not_found_view'
handler400 = 'user.views.my_custom_bad_request_view'
handler403 = 'user.views.my_custom_permission_denied_view'
handler500 = 'user.views.my_custom_error_view'

bonus/models.py
from django.db import models
from userprofile.models import Profile

# Create your models here.
class Bonus(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    usdt_amount = models.FloatField(default=0,null=True,blank=True)
    action = models.TextField(blank=True,null=True)
    seen = models.BooleanField(default=False)
    user_see = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    
    class Meta:
        verbose_name = 'Bonus'
        verbose_name_plural = 'Bonuses'
        ordering = ['-created']
        
    def __str__(self):
        return f'{self.profile.user.username} has been givn a bonus of {self.usdt_amount}'

deposit/models.py
from typing import Iterable, Optional
from django.db import models
from userprofile.models import Profile
import threading
from utils import send_email
#smail
# Create your models here.

class Deposit(models.Model):
    WALLETTYPECHOICES = (
        ('USDT', 'USDT'),
        ('LTC', 'Litecoin'),
        ('BTC', 'Bitcoin'),
        ('XRP','XRP'),
        ('ETH','ETHERUM'),
    )
        
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='deposits')
    created = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=20,decimal_places=5,blank=True,null=True)
    wallet_type  = models.CharField(choices=WALLETTYPECHOICES,max_length=10,blank=True,null=True)
    wallet_address = models.CharField(max_length=100,blank=True,null=True)
    usdt_amount = models.DecimalField(max_digits=20,decimal_places=5,blank=True,null=True)
    verified = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.profile.user.get_username()} deposited {self.usdt_amount} in {self.wallet_address}'
    
    def save(self, *args, **kwargs):
        if self.verified == True:
            self.profile.available_balance +=  float(self.usdt_amount)
            action = f'Your deposit of {self.amount} {self.wallet_type} into {self.wallet_address} is verified'
            self.profile.notification_set.create(profile=self.profile,action='Verified',description=f'Your deposit of {self.amount} {self.wallet_type} into {self.wallet_address} have been verified')
            self.profile.transaction_set.create(profile=self.profile, transaction_type='deposit', usdt_amount=self.usdt_amount, description=action,verified=True)
            self.profile.save()
            try:
                email_thread = threading.Thread(target=send_email,args=('Deposit Verified',f'Your deposit of {self.amount} {self.wallet_type} into {self.wallet_address} is verified',self.profile.user.email))
                email_thread.start()
            except Exception as e:
                print(e)
            
             
        return super().save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        if self.verified == True:
            if float(self.profile.available_balance) > float(self.usdt_amount):
                self.profile.available_balance -=  float(self.usdt_amount)
                self.profile.save()  
        return super().delete(*args, **kwargs)

faq/models.py
from django.db import models

# Create your models here.

 
class FAQ( models.Model):
    question = models.CharField(blank=False,null=False,max_length=100)
    answer = models.TextField(blank=False,null=False)    
    
    class Meta:
        ordering=['-question']
    def __str__(self):
        return f'{self.question} question has been created'

user/models.py
from django.db import models

# Create your models here.

withdraw/models.py
from django.db import models
from userprofile.models import Profile
# Create your models here.

class Withdrawal(models.Model):
    WALLETTYPECHOICES = (
       ('USDT', 'USDT'),
        ('LTC', 'Litecoin'),
        ('BTC', 'Bitcoin'),
        ('XRP','XRP'),
        ('ETH','ETHERUM'),
    )
     
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='withdrawal')
    created = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=20,decimal_places=5,blank=True,null=True)
    wallet_type  = models.CharField(choices=WALLETTYPECHOICES,max_length=10,blank=True,null=True)
    wallet_address = models.CharField(max_length=100,blank=True,null=True)
    usdt_amount = models.DecimalField(max_digits=20,decimal_places=5,blank=True,null=True)
    verified = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.profile.user.get_username} was withdrawn {self.usdt_amount} in {self.wallet_address}'
    
    def save(self, *args, **kwargs):
        if self.verified == True:
            self.profile.available_balance -=  float(self.usdt_amount)
            action = f'Your deposit of {self.amount} {self.wallet_type} into {self.wallet_address} is verified'
            self.profile.notification_set.create(profile=self.profile,action='Verified',description=f'Your deposit of {self.amount} {self.wallet_type} into {self.wallet_address} have been verified')
            self.profile.transaction_set.create(profile=self.profile, transaction_type='withdrawal', usdt_amount=self.usdt_amount, description=action,verified=True)
            self.profile.save() 
        return super().save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        if self.verified == True:
            self.profile.available_balance +=  float(self.usdt_amount)
            self.profile.save()  
        return super().delete(*args, **kwargs)

deposit/forms.py
from django import forms
from .models import *

class DepositForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = '__all__'
        exclude=['profile']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
User = get_user_model()


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
    
    loginemailblocked = forms.BooleanField(required=False)

withdraw/forms.py
from django import forms
from .models import *

class WithdrawalForm(forms.ModelForm):
    class Meta:
        model = Withdrawal
        fields = '__all__'
        exclude=['profile']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

bonus/views.py
from django.shortcuts import render,redirect
from utils import  can_access_dashboard
from django.contrib.auth import get_user_model
User = get_user_model()
from userprofile.models import Profile
from userprofile.decorators import check_profile_exists
from notification.models import Notification
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from transaction.models import Transaction
import threading
from utils import send_email
#smail
from .models import Bonus
# Create your views here.

@login_required(login_url='/accounts/login')
@check_profile_exists
def user_bonus(request):
    
    profile = Profile.objects.get(user=request.user)
    bonuses = Bonus.objects.filter(profile=profile,user_see=True)
    context = {
        'bonuses': bonuses,
        'profile':profile,
        
    }
    return render(request,'user/bonus.html',context)


def dashboard_bonus(request,pk=None):
    if pk == None:
        users = User.objects.all()
        context = {
            'users':users,
                   'user':None
                   }
    else:
        user = User.objects.get(id=pk)
        context = {'user':user,
                   'users':None}
    
    if request.method == 'POST':
        username = request.POST.get('name')
        action = request.POST.get('action')
        amount = request.POST.get('amount')
        user_see = request.POST.get('show_bonus',False)
        
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            messages.error(request,'There was no user with that username')
            return redirect('/bonus/dashboard')
        
        try:
            profile = Profile.objects.get(user=user)
        except Profile.DoesNotExist:
            messages.error(request,'The user does not have a profile')
            return redirect('/bonus/dashboard')
        
        profile.available_balance += float(amount)
        profile.save()
        bonus = Bonus.objects.create(profile=profile,usdt_amount=amount,user_see=user_see,action=action)
        bonus.save()
        
        if user_see:
            transaction = Transaction.objects.create(profile=profile, transaction_type='bonus', usdt_amount=amount, description=f'You have a Bonus of {amount}')
            transaction.save()
            notification = Notification.objects.create(profile=profile, action='Account Credited', description=f'You have a Bonus of {amount}')
            notification.save()
            try:
                email_thread = threading.Thread(target=send_email,args=('Account Credited',f'A Bonus of {amount} has been given to you', profile.user.email))
                email_thread.start()
            except Exception as e:
                print(e)
        messages.success(request,'Your bonus has been sent')
        return redirect('/bonus/dashboard')
    return render(request,'dashboard/bonus.html',context)
 

deposit/views.py
from django.shortcuts import render,redirect
from utils import  can_access_dashboard
from django.contrib.auth import get_user_model
User = get_user_model()
from userprofile.models import Profile
from .models import Deposit
from userprofile.decorators import check_profile_exists
from walletaddress.models import WalletAddress
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from transaction.models import Transaction
import threading
from utils import send_email

from django.conf import settings
from notification.models import Notification
# Create your views here.




@login_required(login_url='/accounts/login')
@check_profile_exists
def user_deposit(request):
    profile = Profile.objects.get(user=request.user)
    deposits = Deposit.objects.filter(profile=profile).order_by('-created')[:5]
    wallet, _ =WalletAddress.objects.get_or_create(pk=1)
    
    context = {
        'wallet':wallet,
        'deposits': deposits,
        'profile':profile, 
    }
 

    if request.method == 'POST':
        wallet_address = request.POST['wallet_address']
        amount = request.POST['amount']
        wallet_type = request.POST['wallet_type']
        usdt_amount = request.POST['usdt_amount']
        
        print(wallet_type)
        deposit = Deposit.objects.create(profile=profile,amount=amount,wallet_type=wallet_type,wallet_address=wallet_address,usdt_amount=usdt_amount)
        deposit.save()
        print(deposit.wallet_type)
        action = f'Your deposit of {deposit.amount} {deposit.wallet_type} into {deposit.wallet_address} is pending'
        notification = Notification.objects.create(profile=profile, action='Deposit Pending', description=action)
        notification.save()
        transaction = Transaction.objects.create(profile=profile, transaction_type='deposit', usdt_amount=usdt_amount, description=action)
        transaction.save()
        
        try:
            email_thread = threading.Thread(target=send_email,args=('Deposit Requested',f'{profile.user.username} has deposited {deposit.amount} {deposit.wallet_type} into {deposit.wallet_address}', settings.RECIPIENT_ADDRESS)        )
            email_thread2 = threading.Thread(target=send_email,args=('Deposit Requested', f'Your deposit of {amount} {wallet_type} into {wallet_address} is pending', request.user.email)        )
            email_thread.start()
            email_thread2.start()
        except Exception as e:
            print(e)
        messages.info(request, 'You have applied for a deposit')
        return redirect('/deposit')
        
    return render(request,'user/deposit.html',context)

def verify(request,id):
    deposit = Deposit.objects.get(id=id)
    if deposit.verified == False:
        deposit.profile.available_balance += int(float(deposit.usdt_amount))
        deposit.profile.save()
        deposit.verified = True
        deposit.save()
    return redirect(request.META.get('HTTP_REFERER', '/admin'))

@login_required(login_url='/accounts/login')
@can_access_dashboard
def dashboard_deposit(request):
    deposits = Deposit.objects.all()
    
    context = {
        'deposits':deposits,
    }
    return render(request,'dashboard/deposit.html',context)

@login_required(login_url='/accounts/login')
@can_access_dashboard
def dashboard_deposit_completed(request):
    deposits = Deposit.objects.filter(verified=True)
    
    context = {
        'deposits':deposits,
    }
    return render(request,'dashboard/deposit3.html',context)

@login_required(login_url='/accounts/login')
@can_access_dashboard
def dashboard_deposit_pending(request):
    deposits = Deposit.objects.filter(verified=False)
    
    context = {
        'deposits':deposits,
    }
    return render(request,'dashboard/deposit4.html',context)

@login_required(login_url='/accounts/login')
@can_access_dashboard
def delete_deposit(request,id):
    deposit = Deposit.objects.get(id=id)
    deposit.delete()
    return redirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/accounts/login')
@check_profile_exists
def user_deposit_completed(request):
    profile = Profile.objects.get(user=request.user)
    deposits = Deposit.objects.filter(profile=profile,verified=True)
    
    
    context = {
        'deposits':deposits,
    }
    return render(request,'user/completeddeposit.html',context)

@login_required(login_url='/accounts/login')
@check_profile_exists
def user_deposit_pending(request):
    profile = Profile.objects.get(user=request.user)
    deposits = Deposit.objects.filter(profile=profile,verified=False)
    
    
    context = {
        'deposits':deposits,
    }
    return render(request,'user/pendingdeposit.html',context)

templates/dashboard/transaction.html
{% extends 'dashboard/main.html' %}

{% load static %}

{% block content %}
<style>
  /* The Modal (background) */
  .modals {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1000000; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }
  
  /* Modal Content/Box */
  .modals-content {
    background-color: #fefefe;
    margin: 2rem auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
  }
  
  /* The Close Button */
  .close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }
  
  .close:hover,
  .close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
  }</style>

   <div class="content-page">
    <div class="content">
     <div class="container-fluid">
      <div class="row">
      </div>
      <div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="usd" role="dialog" style="display: none" tabindex="-1">
      </div>
      <div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="del_tra" role="dialog" style="display: none" tabindex="-1">
      </div>
      <button data-target="#usd" data-toggle="modal" id="show_tra" style="display: none;" type="button">
      </button>
      <button data-target="#del_tra" data-toggle="modal" id="show_del" style="display: none;" type="button">
      </button>

      <div class="row">
        <div class='text-center px-2 py-3 w-100'> {% for message in messages %} <p class="text-center w-100" style="font-size:1.1rem;">{{message}}</p> {% endfor %}</div>

       <div class="col-lg-12">
        <div class="card">
         <div class="card-header bg-primary">
          <h3 class="card-title text-white">
           Transactions
          </h3>
         </div>
         <div class="card-body">
          <div class="row">
           <div class="col-md-12 col-sm-12 col-12">
            <div class="table-responsive">
             <table class="table table-striped table-bordered nowrap" id="datatable" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
              <thead>
               <tr>
                <th>
                 SN
                </th>
                <th>
                 Sender
                </th>
                <th>
                 Amount
                </th>
                <th>
                 Time
                </th>
                <th>
                 Type
                </th>
                <th>
                 Status
                </th>
                <th>
                 View/Delete
                </th>
               </tr>
              </thead>
              <tbody>
               {% for transaction in transactions %}<tr>
                <td>
                 {{ forloop.counter }}
                </td>
                <td>
                 {{transaction.profile.user.username}}
                </td>
                <td>
                 $ {{ transaction.usdt_amount }}
                </td>
                <td>
                 {{ transaction.created}}
                </td>
                <td>
                  {{ transaction }}
                </td>
                <td>
                  {% if transaction.verified %} Verified {% else %} Not Verified {% endif %} 
                </td>
                <td>
                  <button class="btn btn-primary openModalBtn">View</button>
        
                  <div class="modals">
                          <div class="modals-content">
                          <span class="close">&times;</span>
                          <h3>View Transaction</h3>
                          <div class="card-body">

                              <div class="form-group field-profile">
                                  <div class="row">
                                      
                                          <label class="col-sm-3 text-left" for="id_profile">
                                              Profile
                                              
                                          </label>
                                          <div class=" col-sm-7 
                                                        field-profile
                                                       
                                                       
                                                       ">
                                              
                                                  <div class="readonly"><a href="/admin/userprofile/profile/{{profile.id}}/change/">{{profile.user.username}}</a></div>
                                              
                                              
                                              
                                              
                                          </div>
                                      
                                  </div>
                              </div><div class="form-group field-usdt_amount">
                                  <div class="row">
                                      
                                          <label class="col-sm-3 text-left" for="id_usdt_amount">
                                              Usdt amount
                                              
                                          </label>
                                          <div class=" col-sm-7 
                                                        field-usdt_amount
                                                       
                                                       
                                                       ">
                                              
                                                  <div class="readonly">{{transaction.usdt_amount}}</div>
                                              
                                              
                                              
                                              
                                          </div>
                                      
                                  </div>
                              </div>
                              
                              <div class="form-group field-transaction_type">
                                  <div class="row">
                                      
                                          <label class="col-sm-3 text-left" for="id_transaction_type">
                                              Transaction type
                                              
                                          </label>
                                          <div class=" col-sm-7 
                                                        field-transaction_type
                                                       
                                                       
                                                       ">
                                              
                                                  <div class="readonly">{{transaction.transaction_type}}</div>
                                              
                                              
                                              
                                              
                                          </div>
                                      
                                  </div>
                              </div>
                              
                              <div class="form-group field-description">
                                  <div class="row">
                                      
                                          <label class="col-sm-3 text-left" for="id_description">
                                              Description
                                              
                                          </label>
                                          <div class=" col-sm-7 
                                                        field-description
                                                       
                                                       
                                                       ">
                                              
                                                  <div class="readonly">{{transaction.description}}</div>
                                              
                                              
                                              
                                              
                                          </div>
                                      
                                  </div>
                              </div>
                              
                              <div class="form-group field-created">
                                  <div class="row">
                                      
                                          <label class="col-sm-3 text-left" for="id_created">
                                              Created
                                              
                                          </label>
                                          <div class=" col-sm-7 
                                                        field-created
                                                       
                                                       
                                                       ">
                                              
                                                  <div class="readonly">{{transaction.created}}</div>
                                              
                                              
                                              
                                              
                                          </div>
                                      
                                  </div>
                              </div>
                              
                              <div class="form-group field-verified">
                                  <div class="row">
                                      
                                          <label class="col-sm-3 text-left" for="id_verified">
                                              Verified
                                              
                                          </label>
                                          <div class=" col-sm-7 
                                                        field-verified
                                                       
                                                       
                                                       ">
                                                      {% if transaction.verified %}
                                                      
                                                      <div class="readonly"><img src="/static/admin/img/icon-yes.svg" alt="True"></div>
                                                      {% else %}
                                                      <div class="readonly"><img src="/static/admin/img/icon-no.svg" alt="True"></div>
                                                      {% endif %}
                                              
                                                  
                                              
                                              
                                              
                                              
                                          </div>
                                      
                                  </div>
                              </div>
                              
                          
                          
                          
                              
                          
                          
                                                      </div>
                          
                          <div>              
                          </div>
                          </div>
                  </div>
                </td>
               </tr>{% empty %}{% endfor %}
              </tbody>
             </table>
            </div>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </div>
    </div>
    <script>
      var modalButtons = document.querySelectorAll(".openModalBtn");
      var modals = document.querySelectorAll(".modals");
      var closeButtons = document.querySelectorAll(".close");
      
      modalButtons.forEach(function(btn, index) {
        btn.onclick = function() {
          modals[index].style.display = "block";
        }
      });
      
      closeButtons.forEach(function(closeBtn, index) {
        closeBtn.onclick = function() {
          modals[index].style.display = "none";
        }
      });
      
      window.onclick = function(event) {
        modals.forEach(function(modal) {
          if (event.target === modal) {
            modal.style.display = "none";
          }
        });
      }
      </script>
   {% endblock content %}